#!/bin/bash

# This Script sets some additional variables for xt-create-xen-config
# and then calls the real xt-create-xen-config

# bridge for internal IPv4
export bridge_int4=br0
# bridge for external IPv4
export bridge_ext4=br5
# bridge for native IPv6
export bridge6=br9

# generate MAC-Adresses
function generate_ssn_mac() {
	maclist=$(find /etc/xen/ -maxdepth 1 -name "*.cfg" -exec egrep --only-matching "mac=[[:alnum:]:]{17}" {} \; | sed -e "s/mac=//g")
	i=0
	while [ ${i} -lt 100 ]; do
		mac=$(echo -n 00:16:3E:${1}; dd bs=1 count=2 if=/dev/random 2>/dev/null |hexdump -v -e '/1 ":%02X"')
		macisused=false
		for usedmac in ${maclist}; do
			[ ${usedmac} == ${mac} ] && macisused=true
		done
		${macisused} || break
		let i=i+1
	done
	${macisused} || echo ${mac}
}

if [ $(hostname) == deepthought ]; then
	hostidentifier="1A"
	export mac4=$(generate_ssn_mac ${hostidentifier})
	export mac6=$(generate_ssn_mac ${hostidentifier})
elif [ $(hostname) == gazelle ]; then
	hostidentifier="1B"
	export mac4=$(generate_ssn_mac ${hostidentifier})
	export mac6=$(generate_ssn_mac ${hostidentifier})
else
	echo "Cannot generate MAC for $(hostname), please adjust xen-tools.conf"
fi

# IPv6 - Prefixes
export ipv6_prefix_ext="2001:4ca0:200:3:200:5efe"
export ipv6_prefix_int="2001:4ca0:200:3:0:5efe"

/usr/bin/xt-create-xen-config ${@}
