#!/bin/bash

prefix=$1

# source common functions
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    echo "Installation problem in $0"
fi

logMessage Script $0 starting
logMessage "${0}: Setting up resolv.conf"

cat > ${prefix}/etc/resolv.conf <<EOF
search stusta.mhn.de
nameserver 10.150.127.2
nameserver 10.150.125.2
EOF

chroot ${prefix} /usr/bin/aptitude -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --without-recommends install psutils vlan isatapd

chroot ${prefix} /bin/systemctl disable isatapd.service

logMessage My IP is: ${ip1}

if [[ "${ip1}" =~ ^10\.150\.127\..*$ ]] ; then
cat > ${prefix}/etc/network/interfaces <<EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet static
	address ${ip1}
	netmask 255.255.255.0
	gateway 10.150.127.254
	# dns-* options are implemented by the resolvconf package, if installed
	dns-nameservers 10.150.127.2 10.150.125.2
	dns-search stusta.mhn.de
	up isatapd --daemon --check-dns 0 --router 141.84.69.3 --mtu 1280 --name is0 || true
	down killall isatapd || true


auto eth1
iface eth1 inet6 static
	address 2001:4ca0:200:3:0:5efe:${ip1}
	netmask 120
	up ip -6 route add to 2001:4ca0:200:3:200:5efe:141.84.69.0/120 dev \${IFACE} || true
	up ip -6 route add to 2001:4ca0:200:3:0:5efe:10.150.125.0/121 dev \${IFACE} || true
	up ip -6 route add to 2001:4ca0:200:3:0:5efe:10.150.127.0/120 dev \${IFACE} || true
	up ip -6 route add to 2001:4ca0:200:2::/64 dev \${IFACE} || true
	up ip -6 route add to default via 2001:4ca0:200:2::1 || true
EOF

elif [[ "${ip1}" =~ ^141\.84\.69\..*$ ]] ; then
cat > ${prefix}/etc/network/interfaces <<EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet static
	address ${ip1}
	netmask 255.255.255.0
	gateway 141.84.69.254
	# dns-* options are implemented by the resolvconf package, if installed
	dns-nameservers 10.150.127.2 10.150.125.2
	dns-search stusta.mhn.de
	up isatapd --daemon --check-dns 0 --router 141.84.69.3 --mtu 1280 --name is_ext0 || true
	down killall isatapd || true


auto eth1
iface eth1 inet6 static
	address 2001:4ca0:200:3:200:5efe:${ip1}
	netmask 120
	up ip -6 route add to 2001:4ca0:200:3:200:5efe:141.84.69.0/120 dev \${IFACE} || true
	up ip -6 route add to 2001:4ca0:200:3:0:5efe:10.150.125.0/121 dev \${IFACE} || true
	up ip -6 route add to 2001:4ca0:200:3:0:5efe:10.150.127.0/120 dev \${IFACE} || true
	up ip -6 route add to 2001:4ca0:200:2::/64 dev \${IFACE} || true
	up ip -6 route add to default via 2001:4ca0:200:2::1 || true
EOF
fi

logMessage "$0 finished setting up networking"

