#!/bin/sh
#
#  Configure the new image to be a minimal image, by removing
# packages I don't care about - and installing new ones I prefer.

# source common functions
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    echo "Installation problem in $0"
fi

prefix=$1

logMessage "Starting $0"

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    echo "Installation problem in $0"
fi

logMessage Installing/removing packages...

#
#  Install some new packages - do this first to avoid dependency errors.
#
installDebianPackage ${prefix} screen tcpdump mc sudo vim htop locales-all rsync bash-completion

# set LANG
echo "LANG=en_US.UTF-8" > ${prefix}/etc/default/locale


logMessage Installing standard, required and important packages...

disableStartStopDaemon ${prefix}
chroot ${prefix} /usr/bin/aptitude -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install ~pstandard ~prequired ~pimportant portmap- nfs-common-
enableStartStopDaemon ${prefix}

logMessage "Done installing packages by $0"
