#!/bin/sh
#
#  Configure the new image to be a minimal image, by removing
# packages I don't care about - and installing new ones I prefer.

# source common functions
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem in $0"
fi

prefix=$1

logMessage "Starting $0"

# Install some new packages - do this first to avoid dependency errors.

# basics
installDebianPackage ${prefix} python openssl ca-certificates libpam-systemd

# we like kernel updates
installDebianPackage ${prefix} linux-image-amd64

# editors, pagers terminal management
installDebianPackage ${prefix} vim nano less tmux

# <3 z-shell
installDebianPackage ${prefix} zsh bash-completion

# system tools
installDebianPackage ${prefix} sudo htop

# debug tools
installDebianPackage ${prefix} dnsutils tcpdump net-tools netcat

# set LANG
echo "LANG=en_US.UTF-8" > ${prefix}/etc/default/locale


logMessage Installing standard, required and important packages...

disableStartStopDaemon ${prefix}
chroot ${prefix} /usr/bin/aptitude -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install ~pstandard ~prequired ~pimportant portmap- nfs-common- tmux+ sudo+ vim+ htop+ zsh+ linux-image-amd64+
enableStartStopDaemon ${prefix}

logMessage "Done installing packages by $0"
