#!/bin/sh
#
#  Configure PV-Grub

# source common functions
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem in $0"
fi

prefix=$1

logMessage "Starting $0"

installDebianPackage ${prefix} grub2-common

chroot ${prefix} /usr/sbin/update-grub

logMessage "Done installing pvgrub by $0"
