#!/bin/bash
#
#  Passt die /etc/ssh/sshd_conf an
#
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi



#
# Log our start
#
logMessage Script $0 starting


#
#  Install sshd
#
installDebianPackage ${prefix} openssh-server

#cp /etc/ssh/sshd_config /tmp/sshd_config

/usr/sbin/cfagent -K -f - <<EOF
control:
   any::
   actionsequence = ( editfiles )
   EditFileSize = ( 30000 )

editfiles:
   any::
        { ${prefix}/etc/ssh/sshd_config
	  Backup "false"
          HashCommentLinesMatching "^PasswordAuthentication.*$"
          LocateLineMatching "^#* *PasswordAuthentication.*$"
          InsertLine "PasswordAuthentication no"

	  ResetSearch '1'

	  HashCommentLinesMatching "^PermitRootLogin.*$"
          LocateLineMatching "^#* *PermitRootLogin.*$"
          InsertLine "PermitRootLogin no"

          HashCommentLinesMatching ".*_dsa_key$"
          HashCommentLinesMatching "^KeyRegenerationInterval.*$"
          HashCommentLinesMatching "^ServerKeyBits.*$"
          HashCommentLinesMatching "^RSAAuthentication.*$"

	  ResetSearch '1'

	  HashCommentLinesMatching "^X11Forwarding.*$"
          HashCommentLinesMatching "^X11DisplayOffset.*$"
          LocateLineMatching "^#* *X11Forwarding.*$"
          InsertLine "X11Forwarding no"

          IncrementPointer "-2"
          InsertLine "AllowAgentForwarding no"
          InsertLine "AllowTcpForwarding no"
          InsertLine ""
        }
EOF


# Generate stronger SSH-Host-Keys
rm -f ${prefix}/etc/ssh/ssh_host_{dsa,ecdsa,rsa,ed25519}_key{,.pub}

ssh-keygen -t rsa   -b 4096 -f ${prefix}/etc/ssh/ssh_host_rsa_key     -N "" -C "root@${hostname}"
ssh-keygen -t ed25519       -f ${prefix}/etc/ssh/ssh_host_ed25519_key -N "" -C "root@${hostname}"



#
#  Log our finish
#
logMessage Script $0 finished

