#!/bin/bash
#

prefix=$1

# source common functions
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi

# get hostname
hostname=$(cat ${prefix}/etc/hostname)

logMessage Hostname is \"${hostname}\"

# install exim
logMessage Installing exim...
installDebianPackage ${prefix} exim4 exim4-base exim4-config exim4-daemon-light

# set debconf selections for exim
logMessage Configuring exim...
chroot ${prefix} /usr/bin/debconf-set-selections <<EOF
#exim4-daemon-light      exim4-daemon-light/drec error   
exim4-config    exim4/dc_other_hostnames        string  ${hostname}.stusta.mhn.de
exim4-config    exim4/dc_eximconfig_configtype  select  mail sent by smarthost; no local mail
exim4-config    exim4/no_config boolean true
exim4-config    exim4/hide_mailname     boolean true
exim4-config    exim4/dc_postmaster     string  vorstand-tv@lists.stusta.mhn.de
exim4-config    exim4/dc_smarthost      string  mail.stusta.mhn.de
exim4-config    exim4/dc_relay_domains  string  
exim4-config    exim4/dc_relay_nets     string  
exim4-base      exim4/purge_spool       boolean false
exim4-config    exim4/mailname  string  ${hostname}.stusta.mhn.de
exim4-config    exim4/dc_readhost       string  ${hostname}.stusta.mhn.de
#exim4   exim4/drec      error   
#exim4-base      exim4-base/drec error   
exim4-config    exim4/use_split_config  boolean true
exim4-config    exim4/dc_localdelivery  select  mbox format in /var/mail/
exim4-config    exim4/dc_local_interfaces       string  127.0.0.1 ; ::1
exim4-config    exim4/dc_minimaldns     boolean false
EOF

# ugly hack because debconf does not work properly...
logMessage Ugly hack: Patching /etc/exim4/update-exim4.conf.conf
cat > ${prefix}/etc/exim4/update-exim4.conf.conf <<EOF
# /etc/exim4/update-exim4.conf.conf
#
# Edit this file and /etc/mailname by hand and execute update-exim4.conf
# yourself or use 'dpkg-reconfigure exim4-config'
#
# Please note that this is _not_ a dpkg-conffile and that automatic changes
# to this file might happen. The code handling this will honor your local
# changes, so this is usually fine, but will break local schemes that mess
# around with multiple versions of the file.
#
# update-exim4.conf uses this file to determine variable values to generate
# exim configuration macros for the configuration file.
#
# Most settings found in here do have corresponding questions in the
# Debconf configuration, but not all of them.
#
# This is a Debian specific file

dc_eximconfig_configtype='satellite'
dc_other_hostnames='${hostname}.stusta.mhn.de'
dc_local_interfaces='127.0.0.1 ; ::1'
dc_readhost='${hostname}.stusta.mhn.de'
dc_relay_domains=''
dc_minimaldns='false'
dc_relay_nets=''
dc_smarthost='mail.stusta.mhn.de'
CFILEMODE='644'
dc_use_split_config='true'
dc_hide_mailname='true'
dc_mailname_in_oh='true'
dc_localdelivery='mail_spool'
EOF

# set SSN-rewrite rules
echo *@${hostname}.stusta.mhn.de no-reply@mail.stusta.mhn.de Frs > ${prefix}/etc/exim4/conf.d/rewrite/99_ssn_no-reply_rewriting

# reconfigure exim
logMessage Reconfiguring exim...
disableStartStopDaemon ${prefix}
chroot ${prefix} /usr/sbin/dpkg-reconfigure --unseen-only -pcritical exim4-config
enableStartStopDaemon ${prefix}

logMessage Exim done...
