#!/bin/bash
#

prefix=$1

# source common functions
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi

/usr/sbin/cfagent -K -f - <<EOF

control:
   any::
   actionsequence = ( editfiles )
   EditFileSize = ( 30000 )

editfiles:
   any::
        { ${prefix}/etc/systemd/timesyncd.conf
	  Backup "false"
          LocateLineMatching "^#Servers=.*"
          InsertLine "Servers=10.150.127.2 10.150.125.2"
        }
EOF

chroot ${prefix} /bin/systemctl enable systemd-timesyncd.service


logMessage systemd-timesyncd done...

