#!/bin/bash
#
#  Legt die Admin-Accounts an
#
#

techvorstand1=007394
techvorstand2=007553
techvorstand3=010584

prefix=$1
admins=${techvorstand1},${techvorstand2},${techvorstand3},$2

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi



#
# Log our start
#
logMessage Script $0 starting

IFS=","
for user in ${admins}; do
	if [ -f "/etc/xen-tools/admin.d/${user}.key" -a -f "/etc/xen-tools/admin.d/${user}.pw" -a -f "/etc/xen-tools/admin.d/${user}.name" -a -f "/etc/xen-tools/admin.d/${user}.mail" ]; then
		logMessage Script adding a${user}a...
		chroot ${prefix} useradd  -p "`cat /etc/xen-tools/admin.d/${user}.pw`" -c "`cat /etc/xen-tools/admin.d/${user}.name`" a${user}a -m -ou 0
        mkdir -m 700 ${prefix}/home/a${user}a/.ssh
		install -m 644 /etc/xen-tools/admin.d/${user}.key ${prefix}/home/a${user}a/.ssh/authorized_keys
		chroot ${prefix} chown -R root:root /home/a${user}a/.ssh

		if [ -s "/etc/xen-tools/admin.d/${user}.mail" && ${user} != ${techvorstand1} && ${user} != ${techvorstand2} && ${user} != ${techvorstand3}]; then
		mail=`cat /etc/xen-tools/admin.d/${user}.mail`
		/usr/sbin/cfagent -K -f - <<-EOF
		control:
		   any::
		   actionsequence = ( editfiles )
		   EditFileSize = ( 30000 )

		editfiles:
		   any::
		        { ${prefix}/etc/aliases
			  Backup "false"
			  LocateLineMatching "^root:.*$"
         		  AppendToLineIfNotContains ", ${mail}"
			}
		EOF
		logMessage Scrip: user a${user}a mail addy ${mail} added to /etc/aliases...
		fi




	else
		logMessage Script ERROR: user a${user}a not found...
	fi
done
#
#  Log our finish
#
logMessage Script $0 finished
