#!/bin/sh
#
# Install grub for pygrub

# source common functions
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem in $0"
fi

prefix=$1

logMessage "Starting $0"

chroot ${prefix} /usr/bin/apt autoremove
chroot ${prefix} /usr/bin/apt autoclean

logMessage "Done cleaning by $0"

